<?php

namespace Database\Seeders;

use App\Models\Formation;
use Illuminate\Database\Seeder;

class FormationSeeder extends Seeder
{
    public function run(): void
    {
        Formation::truncate();

        $formations = [

            // ─── ANNÉES PRÉPARATOIRES ────────────────────────────────────────────────
            [
                'slug'         => 'annees-preparatoires',
                'title'        => 'Années Préparatoires (CP1 & CP2)',
                'category'     => 'preparatoire',
                'type'         => 'preparatoire',
                'duree_annees' => 2,
                'source_url'   => 'https://ensa.uit.ac.ma/preparatory-years/',
                'description'  => 'Les classes préparatoires intégrées des ENSA permettent aux étudiants d\'intégrer une formation d\'ingénieur dès leur première année universitaire. Elles s\'étendent sur deux années et couvrent les matières fondamentales nécessaires pour aborder le cycle ingénieur. L\'admission en cycle ingénieur ne nécessite pas de concours national : les étudiants passent automatiquement au cycle ingénieur s\'ils valident les deux années préparatoires.',
                'objectifs'    => [
                    'Acquérir les bases mathématiques, physiques et informatiques pour le cycle ingénieur',
                    'Développer une formation scientifique et technique solide',
                    'Développer les compétences en communication, travail en équipe et gestion de projet',
                    'Bénéficier d\'un encadrement académique de qualité dans un environnement stimulant',
                ],
                'competences'  => [
                    'CP1' => [
                        'Mathématiques : Analyse, algèbre, probabilités',
                        'Physique : Mécanique, thermodynamique, électricité',
                        'Informatique : Introduction aux langages de programmation, algorithmes',
                        'Chimie : Bases de la chimie organique et inorganique',
                        'Langues : Renforcement en français et anglais',
                    ],
                    'CP2' => [
                        'Mathématiques avancées : Calcul différentiel, statistiques, algèbre linéaire',
                        'Physique appliquée : Électromagnétisme, optique, physique des matériaux',
                        'Sciences de l\'ingénieur : Mécanique des fluides, résistance des matériaux',
                        'Informatique avancée : Programmation orientée objet, structures de données',
                        'Projets et travaux pratiques',
                    ],
                ],
                'programme'    => [
                    'S1' => [
                        'M111 – Analyse 1',
                        'M112 – Algèbre 1',
                        'M113 – Mécanique du point matériel',
                        'M114 – Chimie générale',
                        'M115 – Dessin technique',
                        'M116 – Méthodologie de travail universitaire',
                        'M117 – Langues étrangères (Anglais/Français)',
                    ],
                    'S2' => [
                        'M121 – Analyse 2',
                        'M122 – Thermodynamique et Statique des Fluides',
                        'M123 – Culture digitale',
                        'M124 – Langues étrangères (Anglais/Français)',
                        'M125 – Electrostatique et Magnétostatique',
                        'M126 – Algorithmique',
                        'M127 – Algèbre 2',
                    ],
                    'S3' => [
                        'M231 – Mécanique du solide',
                        'M232 – Algèbre 3',
                        'M233 – Culture and art skills',
                        'M234 – Electrocinétique',
                        'M235 – Langage C',
                        'M236 – Langues étrangères (Anglais/Français)',
                        'M237 – Analyse 3',
                    ],
                    'S4' => [
                        'M241 – Électromagnétisme et Physique des ondes',
                        'M242 – Langues étrangères (Anglais/Français)',
                        'M243 – Electronique analogique et numérique',
                        'M244 – Développement personnel',
                        'M245 – Analyse Numérique et Probabilités',
                        'M246 – Optique Géométrique et Optique Physique',
                        'M247 – Analyse 4',
                    ],
                ],
                'acces'        => [
                    'Baccalauréat scientifique (série Sciences & Technologies, Sciences de la matière, Sciences Mathématiques)',
                    'Sélection sur dossier scolaire',
                ],
                'debouches'    => ['Accès direct au Cycle Ingénieur ENSA sans concours national'],
                'partenariats' => [],
            ],

            // ─── GÉNIE INFORMATIQUE ──────────────────────────────────────────────────
            [
                'slug'         => 'genie-informatique',
                'title'        => 'Génie Informatique',
                'category'     => 'cycle_ingenieur',
                'type'         => 'ingenieur',
                'duree_annees' => 3,
                'source_url'   => 'https://ensa.uit.ac.ma/computer-engineering/',
                'description'  => 'La formation en Génie Logiciel, Big Data et Data Science vise à former des ingénieurs polyvalents maîtrisant la conception et le déploiement de systèmes logiciels complexes et solutions Big Data. Elle propose deux options de spécialisation : Big Data & Data Science et Génie Logiciel.',
                'objectifs'    => [
                    'Acquérir une solide formation en programmation, bases de données et réseaux',
                    'Maîtriser les technologies modernes (Frameworks web, Git, CI/CD, Hadoop, Spark)',
                    'Développer une expertise en méthodologies Agile et principes de conception logicielle',
                    'Acquérir des compétences solides en analyse de données et Machine Learning',
                    'Comprendre les architectures Big Data et les systèmes de traitement distribué',
                    'Intégrer les principes de sécurité dans la conception des systèmes logiciels',
                    'Encourager l\'innovation et l\'entrepreneuriat',
                ],
                'competences'  => [
                    'Fondamentaux' => [
                        'Concevoir, administrer et optimiser des bases de données relationnelles et NoSQL',
                        'Développer des applications web et mobile modernes et intégrer des services API',
                        'Maîtriser l\'administration des systèmes d\'exploitation',
                        'Sécuriser les réseaux et systèmes informatiques contre les cybermenaces',
                    ],
                    'Développement logiciel' => [
                        'Industrialiser avec les méthodes Agile et les outils de développement intégrés',
                        'Concevoir et déployer des architectures distribuées',
                        'Créer et déployer des services web dans des environnements cloud',
                    ],
                    'Big Data & IA' => [
                        'Exploiter les technologies du Big Data pour le traitement de grands volumes de données',
                        'Concevoir et implémenter des algorithmes de Machine Learning et Deep Learning',
                        'Créer des pipelines d\'orchestration de données',
                        'Visualiser et analyser les données pour en extraire des insights stratégiques',
                    ],
                ],
                'programme'    => [
                    'S1' => [
                        'Statistique Inférentielle (4 cr)',
                        'Complexité et Structures de Données (5 cr)',
                        'Réseaux Informatique (5 cr)',
                        'Électronique Numérique (5 cr)',
                        'Systèmes d\'Information et Bases de Données (5 cr)',
                        'Langues Étrangères (3 cr)',
                        'Digitalisation (3 cr)',
                    ],
                    'S2' => [
                        'Technologies Web (5 cr)',
                        'Modélisation et Simulation des Systèmes (5 cr)',
                        'Optimisation des Systèmes (5 cr)',
                        'Technologies de Communication (5 cr)',
                        'Programmation Objet (4 cr)',
                        'Langues Étrangères (3 cr)',
                        'Droit, Civisme et Citoyenneté (3 cr)',
                    ],
                    'S3' => [
                        'Advanced Python (5 cr)',
                        'Systèmes d\'Exploitation (5 cr)',
                        'MultiMedia et Traitement d\'Image (4 cr)',
                        'Ingénierie des Bases de Données (5 cr)',
                        'Programmation Java (5 cr)',
                        'Langues Étrangères (3 cr)',
                        'Introduction à l\'Intelligence Artificielle (3 cr)',
                    ],
                    'S4 – Option Big Data & Data Science' => [
                        'Fondamentaux des Big Data (5 cr)',
                        'Intelligence Artificielle Avancée (5 cr)',
                        'Gouvernance et Gestion des Données (5 cr)',
                        'Analyse et Visualisation des Données (5 cr)',
                        'Cybersécurité (4 cr)',
                        'Langues Étrangères (3 cr)',
                        'Management de l\'entreprise (3 cr)',
                    ],
                    'S4 – Option Génie Logiciel' => [
                        'Développement Full Stack (5 cr)',
                        'Développement Mobile (5 cr)',
                        'UX/UI Design (4 cr)',
                        'Administration et Programmation Système (5 cr)',
                        'Datawarehouse et Datamining (5 cr)',
                        'Langues Étrangères (3 cr)',
                        'Management de l\'entreprise (3 cr)',
                    ],
                    'S5 – Option Big Data & Data Science' => [
                        'Big Data Avancées (5 cr)',
                        'Vision par Ordinateur et Deep Learning (5 cr)',
                        'Intelligence d\'Affaires pour Big Data (5 cr)',
                        'Cloud et Virtualisation (4 cr)',
                        'Sécurité des Données (5 cr)',
                        'Langues Étrangères (3 cr)',
                        'Compétences pour l\'Emploi (3 cr)',
                    ],
                    'S5 – Option Génie Logiciel' => [
                        'Génie Logiciel et Architecture logicielle (5 cr)',
                        'Développement JEE (5 cr)',
                        'Patrons de Conception et Tests Logiciels (5 cr)',
                        'Gestion des Processus Métiers et CRM (4 cr)',
                        'DevOps (5 cr)',
                        'Langues Étrangères (3 cr)',
                        'Compétences pour l\'Emploi (3 cr)',
                    ],
                ],
                'debouches'    => [
                    'Développement & Architecture' => ['Ingénieur fullstack', 'Architecte logiciel', 'Expert DevOps'],
                    'Data & Analyse'               => ['Data Scientist', 'Ingénieur Big Data', 'Analyste Business Intelligence'],
                    'Sécurité & Systèmes'          => ['Expert cybersécurité', 'Administrateur systèmes', 'Ingénieur cloud'],
                    'Management & Innovation'       => ['Chef de projet IT', 'Consultant en transformation digitale', 'Product Owner'],
                ],
                'acces'        => [
                    'Diplômes requis : 2 années préparatoires cycle ingénieur ou équivalent (DEUG, DEUST, DUT)',
                    'Spécialités recommandées : Sciences mathématiques, Sciences & technologies, Informatique',
                ],
                'partenariats' => [],
            ],

            // ─── GÉNIE ÉLECTRIQUE ────────────────────────────────────────────────────
            [
                'slug'         => 'genie-electrique',
                'title'        => 'Génie Électrique',
                'category'     => 'cycle_ingenieur',
                'type'         => 'ingenieur',
                'duree_annees' => 3,
                'source_url'   => 'https://ensa.uit.ac.ma/electrical-engineering/',
                'description'  => 'La formation en Génie Électrique prépare des ingénieurs capables de répondre aux défis des secteurs de l\'énergie, de l\'électronique de puissance, de l\'automatisme, de l\'IA embarquée et de la robotique. Elle intègre deux axes de spécialisation : TERI (Transition Énergétique et Réseaux Intelligents) et SEIA (Systèmes Embarqués et Intelligence Artificielle). La filière encourage l\'ouverture internationale avec des partenariats de double diplôme.',
                'objectifs'    => [
                    'Maîtriser l\'électronique, l\'électronique de puissance et l\'automatisme',
                    'Concevoir des systèmes IoT intelligents avec intégration cloud/edge computing',
                    'Piloter et superviser des procédés industriels en temps réel',
                    'Concevoir et dimensionner des installations de production décentralisée (énergies renouvelables)',
                    'Gérer la qualité de l\'énergie et la stabilité des réseaux électriques',
                    'Déployer des modèles IA sur plateformes embarquées',
                ],
                'competences'  => [
                    'Systèmes Embarqués et IA' => [
                        'Conception et développement de systèmes embarqués et temps réel',
                        'Conception de systèmes IoT intelligents',
                        'Cybersécurité des systèmes embarqués et communicants',
                        'Déploiement de modèles IA sur plateformes embarquées',
                    ],
                    'Transition Energétique et Réseaux Intelligents' => [
                        'Conception et dimensionnement des installations de production décentralisée',
                        'Gestion de la qualité de l\'énergie et de la stabilité des réseaux',
                        'Modélisation et optimisation des chaînes de conversion de l\'énergie',
                        'Intégration des véhicules électriques et des systèmes de stockage',
                    ],
                    'Compétences Transversales' => [
                        'Rédaction de documents techniques et communication',
                        'Maîtrise des concepts mathématiques appliqués',
                        'Adaptabilité et aptitude au travail en équipe',
                    ],
                ],
                'programme'    => [
                    'S5' => [
                        'Maths pour Ingénieur 1',
                        'Ondes/propagation & antennes',
                        'Electronique analogique',
                        'Circuits électriques et magnétiques',
                        'Transfert thermique et Mécanique des fluides',
                        'Langues Étrangères 1',
                        'Compétences Numériques & Programmation',
                    ],
                    'S6' => [
                        'Capteurs et Actionneurs',
                        'Machines à courant continu et schémas électrotechniques',
                        'Electronique numérique avancée',
                        'Electronique de Puissance 1',
                        'Asservissement Continu et échantillonné',
                        'Langues Étrangères 2',
                        'Culture & arts & sport skills',
                    ],
                    'S7' => [
                        'Informatique Industrielle',
                        'Machines Synchrones et Asynchrones',
                        'Transmission numérique – Réseaux Informatiques',
                        'Electronique de Puissance 2',
                        'Régulation industrielle et intelligente',
                        'Langues Étrangères 3',
                        'Introduction à l\'Intelligence Artificielle',
                    ],
                    'S8' => [
                        'Association Convertisseur Machine – Entraînement variable [TERI]',
                        'Analyse et CAO Circuits intégrés [SEIA]',
                        'Systèmes automatisés et IHM',
                        'Production d\'énergie et énergies renouvelables [TERI]',
                        'Informatique & Intelligence Embarquées [SEIA]',
                        'Systèmes multivariables, commande optimale et prédictive',
                        'Réseaux Électriques [TERI]',
                        'Systèmes embarqués et temps réel [SEIA]',
                        'Langues Étrangères 4',
                        'Gestion de l\'entreprise et son environnement Économique',
                    ],
                    'S9' => [
                        'Transport Énergie et stabilité Réseaux [TERI]',
                        'Robotique industrielle et collaborative [SEIA]',
                        'Communication industrielle et Supervision',
                        'Réseaux électriques intelligents : Génération distribuée [TERI]',
                        'Apprentissage Artificiel et Vision par Ordinateur [SEIA]',
                        'Mobilité verte [TERI]',
                        'Systèmes embarqués – véhicule autonome [SEIA]',
                        'Qualité et management de l\'énergie [TERI]',
                        'Internet des Objets et Systèmes Cyberphysiques [SEIA]',
                        'Langues Étrangères 5',
                        'Employment Skills',
                    ],
                    'S10' => ['Projet de Fin d\'Études (PFE) – durée minimale 4 mois'],
                ],
                'debouches'    => [
                    'Ingénieur smart grid / réseaux intelligents',
                    'Ingénieur en intelligence artificielle embarquée',
                    'Ingénieur énergies renouvelables',
                    'Ingénieur en mobilité électrique',
                    'Chef de projet en intégration de sources renouvelables',
                    'Chef de projet en systèmes connectés',
                    'Consultant en transition énergétique',
                    'Doctorat dans un domaine de pointe (IA, smart grids, systèmes critiques…)',
                ],
                'acces'        => [
                    'Diplômes requis : 2 années préparatoires cycle ingénieur / en ingénierie, DEUG, DEUST, DEUP, DUT',
                    'Spécialités recommandées : Sciences de l\'ingénieur, Sciences de la matière / physique, Sciences & technologies',
                ],
                'partenariats' => [
                    'Polytech TOURS',
                    'Polytech LILLE (double diplôme et mobilité)',
                    'Polytech Angers',
                    'Polytech Nantes',
                    'INSA Centre Val de Loire (double diplôme et mobilité)',
                    'ESIX',
                ],
            ],

            // ─── GÉNIE INDUSTRIEL ────────────────────────────────────────────────────
            [
                'slug'         => 'genie-industriel',
                'title'        => 'Génie Industriel',
                'category'     => 'cycle_ingenieur',
                'type'         => 'ingenieur',
                'duree_annees' => 3,
                'source_url'   => 'https://ensa.uit.ac.ma/industrial-engineering/',
                'description'  => 'La formation en Génie Industriel prépare des ingénieurs capables de concevoir, optimiser et gérer des systèmes complexes intégrant les nouvelles technologies. Les lauréats gèrent des projets industriels nationaux et internationaux en intégrant les enjeux humains, environnementaux et économiques, dans le respect de l\'éthique, du développement durable et des réglementations.',
                'objectifs'    => [
                    'Maîtriser les outils et techniques de l\'ingénierie industrielle (modélisation, simulation, optimisation)',
                    'Gérer la complexité des systèmes industriels modernes',
                    'Développer des compétences en gestion de la chaîne d\'approvisionnement globale et logistique',
                    'Mettre en œuvre le Lean Manufacturing et le Six Sigma',
                    'Optimiser les performances et l\'efficacité des processus industriels',
                    'Favoriser l\'innovation technologique et l\'usine du futur',
                ],
                'competences'  => [
                    'Concevoir, piloter et améliorer un système industriel et la chaîne logistique',
                    'Manager des équipes multidisciplinaires et des projets d\'amélioration continue',
                    'Anticiper les évolutions et intégrer les innovations de l\'usine du futur',
                    'Gérer des projets industriels avec une dimension nationale et internationale',
                ],
                'programme'    => [
                    'S5' => [
                        'Statistiques Inférentielle (4 cr)',
                        'Réseaux et Protocoles (5 cr)',
                        'Complexité et Structures de données (5 cr)',
                        'Systèmes d\'information et Technologies des bases de données (5 cr)',
                        'Électronique numérique et analogique (5 cr)',
                        'Compétences Numériques et Programmation (3 cr)',
                        'Langues (3 cr)',
                    ],
                    'S6' => [
                        'Optimisation et Systèmes Industriels (5 cr)',
                        'Développement WEB (5 cr)',
                        'Modélisation et simulation numérique pour l\'industrie (5 cr)',
                        'POO (4 cr)',
                        'Télécommunications et communication des systèmes intelligents (5 cr)',
                        'Langues (3 cr)',
                        'Citoyenneté et vie publique (3 cr)',
                    ],
                    'S7' => [
                        'Management de la Qualité et Excellence Opérationnelle (5 cr)',
                        'CFAO et Procédés Industriels (5 cr)',
                        'Gestion de la Production (5 cr)',
                        'Analyse Financière et Gestion des coûts (4 cr)',
                        'SCM (5 cr)',
                        'Langues (3 cr)',
                        'Introduction à l\'IA (3 cr)',
                    ],
                    'S8' => [
                        'IA for Industrial Business Process Management (5 cr)',
                        'Management de la maintenance et Sûreté de fonctionnement (5 cr)',
                        'Systèmes d\'Informations Intégrés (ERP) (5 cr)',
                        'Ordonnancement (5 cr)',
                        'Automatisme et Robotique (4 cr)',
                        'Langues (3 cr)',
                        'Management de l\'entreprise (3 cr)',
                    ],
                    'S9' => [
                        'Performance, Durabilité et Résilience (5 cr)',
                        'Industrial Data Driving et prise de décision (5 cr)',
                        'Analyse de Données Intelligente pour l\'Ingénierie Industrielle (5 cr)',
                        'Cloud et Cybersécurité (4 cr)',
                        'Réalité Étendue (XR) et Vision Industrielle (5 cr)',
                        'Langues (3 cr)',
                        'Employment Skills (3 cr)',
                    ],
                    'S10' => ['Projet de Fin d\'Études (PFE) (30 cr)'],
                ],
                'debouches'    => [
                    'Ingénieur en production, supply chain et qualité',
                    'Ingénieur en maintenance',
                    'Ingénieur en robotique et automatisation',
                    'Consultant en ingénierie industrielle',
                    'Chef de projet industriel',
                ],
                'acces'        => [
                    'Diplômes requis : 2 années préparatoires cycle ingénieur ou équivalent',
                    'Spécialités recommandées : Sciences de l\'ingénieur, Sciences & technologies',
                ],
                'partenariats' => [],
            ],

            // ─── GÉNIE MÉCATRONIQUE ──────────────────────────────────────────────────
            [
                'slug'         => 'genie-mecatronique',
                'title'        => 'Génie Mécatronique',
                'category'     => 'cycle_ingenieur',
                'type'         => 'ingenieur',
                'duree_annees' => 3,
                'source_url'   => 'https://ensa.uit.ac.ma/automotive-mechatronics-engineering/',
                'description'  => 'La spécialité mécatronique forme des ingénieurs aptes à développer des projets pluridisciplinaires intégrant informatique, automatisme, électronique et mécanique. La filière est orientée vers le secteur automobile, secteur émergent prioritaire au Maroc, et allie études théoriques et réalisations pratiques.',
                'objectifs'    => [
                    'Développer des projets pluridisciplinaires intégrant informatique, automatisme, électronique et mécanique',
                    'Spécialiser les étudiants dans le secteur automobile',
                    'Former des ingénieurs polyvalents capables de s\'intégrer dans l\'industrie moderne',
                ],
                'competences'  => [
                    'Techniques fondamentales' => [
                        'Informatique industrielle',
                        'Automatisme',
                        'Électronique',
                        'Systèmes embarqués',
                        'Robotique',
                        'Mécanique',
                    ],
                    'Transversales' => [
                        'Maîtrise de langues étrangères',
                        'Conduite de projet',
                        'Management des ressources humaines',
                        'Gestion des ressources financières',
                    ],
                    'Gestion et production' => [
                        'Gérer efficacement une cellule de production',
                        'Superviser un travail de groupe',
                        'S\'intégrer efficacement au sein d\'une entité privée ou publique',
                    ],
                ],
                'programme'    => [
                    '1ère année' => ['Programme disponible en PDF sur le site ENSA'],
                    '2ème année' => ['Programme disponible en PDF sur le site ENSA'],
                    '3ème année' => ['Programme disponible en PDF sur le site ENSA'],
                ],
                'debouches'    => [
                    'Ingénieur mécatronique dans le secteur automobile',
                    'Ingénieur en systèmes embarqués',
                    'Ingénieur en robotique',
                    'Responsable de production',
                    'Chef de projet mécatronique',
                ],
                'acces'        => [
                    'Diplômes requis : 2 années préparatoires cycle ingénieur ou équivalent',
                    'Spécialités recommandées : Sciences de l\'ingénieur, Mécanique, Électronique',
                ],
                'partenariats' => [],
            ],

            // ─── GÉNIE DES RÉSEAUX ET TÉLÉCOMMUNICATIONS ────────────────────────────
            [
                'slug'         => 'genie-reseaux-telecommunications',
                'title'        => 'Génie des Réseaux et Systèmes de Télécommunication',
                'category'     => 'cycle_ingenieur',
                'type'         => 'ingenieur',
                'duree_annees' => 3,
                'source_url'   => 'https://ensa.uit.ac.ma/networks-and-telecommunications-systems/',
                'description'  => 'Cette formation prépare les étudiants à une carrière dans le domaine des réseaux et des systèmes de télécommunication. Elle propose trois options de spécialisation : Sécurité des Réseaux et des Systèmes d\'Information, Ingénierie des Systèmes Connectés et Réseaux Mobiles, et Ingénierie des Systèmes Ubiquitaires.',
                'objectifs'    => [
                    'Acquérir une connaissance approfondie des principes fondamentaux des réseaux',
                    'Se familiariser avec les réseaux cellulaires, de données, sans fil, satellites et optiques',
                    'Concevoir, mettre en œuvre, gérer et maintenir des réseaux et systèmes de télécommunication',
                    'Apprendre les principes de sécurité des réseaux et des systèmes de télécommunication',
                    'Suivre les évolutions rapides et appliquer des technologies innovantes (5G/6G, IoT)',
                    'Développer des compétences en travail d\'équipe et gestion de projet',
                ],
                'competences'  => [
                    'Comprendre et maîtriser les architectures, protocoles et technologies des réseaux câblés, sans fil, mobiles et optiques',
                    'Configurer, installer et maintenir des équipements réseau (routeurs, commutateurs, points d\'accès)',
                    'Gérer et administrer des systèmes de télécommunication à grande échelle',
                    'Concevoir et déployer des réseaux efficaces en tenant compte de la bande passante, latence et sécurité',
                    'Comprendre les principes de base de la sécurité réseau et mettre en œuvre des stratégies de protection',
                    'Maîtriser la virtualisation des réseaux (SDN) et le cloud computing',
                    'Suivre les évolutions technologiques : 5G/6G, environnements connectés intelligents',
                ],
                'programme'    => [
                    'S5 (Tronc commun)' => [
                        'Systèmes d\'Information et Technologies des Bases de Données',
                        'Electronique Analogique et Numérique',
                        'Complexité des Algorithmes et Structures de données',
                        'Statistique Inférentielle',
                        'Réseaux Locaux et Protocoles',
                        'Langues Étrangères I',
                        'Compétences Numériques et Programmation',
                    ],
                    'S6 (Tronc commun)' => [
                        'Modélisation et Simulation Numérique pour l\'Industrie',
                        'Technologies Web',
                        'Optimisation et Systèmes Industriels',
                        'Technologies de Communication pour Systèmes Intelligents',
                        'Programmation Orientée Objet',
                        'Langues Étrangères 2',
                        'Droit, Civisme et Citoyenneté',
                        'Stage',
                    ],
                    'S7 (Tronc commun)' => [
                        'Signaux et Systèmes pour les Télécommunications',
                        'Réseaux Étendus et Protocoles',
                        'Ingénierie des Réseaux Fixes et Mobiles',
                        'Systèmes Microprogrammés',
                        'Communications Numériques',
                        'Langues Étrangères 3',
                        'Introduction à l\'Intelligence Artificielle',
                    ],
                    'S8 – Option Sécurité des Réseaux' => [
                        'Cryptographie et Stéganographie',
                        'Connectivité Cellulaire et Réseaux Mobiles Avancés',
                        'Théorie de l\'Information et Codage de Canal',
                        'Administration et Sécurité des Systèmes et Réseaux',
                        'Communications Optiques et Satellitaires',
                        'Langues Étrangères 4',
                        'Stage',
                    ],
                    'S8 – Option Systèmes Connectés et Réseaux Mobiles' => [
                        'Data Science',
                        'Connectivité Cellulaire et Réseaux Mobiles Avancés',
                        'SDN Cloud et Virtualisation',
                        'Communications Optiques et Satellitaires',
                        'Langues Étrangères 4',
                        'Stage',
                    ],
                    'S8 – Option Systèmes Ubiquitaires' => [
                        'Data Science',
                        'IoT/WSN pour la Transformation Numérique',
                        'Communications Optiques et Satellitaires',
                        'Langues Étrangères 4',
                        'Stage',
                    ],
                    'S9 – Option Sécurité des Réseaux' => [
                        'Sécurité des Réseaux Mobiles et Sans Fil',
                        'IA Appliquée aux Télécoms',
                        'Cybersécurité, Blockchain et GRC',
                        'Communications Mobiles et Radio Logicielle',
                        'Sécurité des Infrastructures Critiques',
                        'PFE',
                    ],
                    'S9 – Option Systèmes Connectés et Réseaux Mobiles' => [
                        'Vision Par Ordinateur',
                        'IA Appliquée aux Télécoms',
                        'Systèmes 5G et Environnements Intelligents',
                        'Antennes et Radars',
                        'PFE',
                    ],
                    'S9 – Option Systèmes Ubiquitaires' => [
                        'Ingénierie RF et Microonde',
                        'IA Appliquée aux Télécoms',
                        'Systèmes Embarqués Temps Réel',
                        'Conception des Circuits VLSI',
                        'PFE',
                    ],
                ],
                'debouches'    => [
                    'Ingénieur réseau, administrateur réseaux et système',
                    'Ingénieur en sécurité réseau et systèmes, expert cybersécurité',
                    'Architecte réseau',
                    'Spécialiste en télécommunications (fixe, mobile, données)',
                    'Ingénieur cloud et virtualisation',
                    'Expert en IoT',
                    'Ingénieur en télécommunications mobiles (5G/6G)',
                    'Chercheur en technologies mobiles et IoT',
                ],
                'acces'        => [
                    'Diplômes requis : 2 années préparatoires cycle ingénieur ou équivalent',
                    'Spécialités recommandées : Sciences de l\'ingénieur, Électronique, Informatique, Télécommunications',
                ],
                'partenariats' => [],
            ],

            // ─── EFFICACITÉ ÉNERGÉTIQUE ET BÂTIMENT INTELLIGENT ─────────────────────
            [
                'slug'         => 'efficacite-energetique-batiment-intelligent',
                'title'        => 'Efficacité Énergétique et Bâtiment Intelligent',
                'category'     => 'cycle_ingenieur',
                'type'         => 'ingenieur',
                'duree_annees' => 3,
                'source_url'   => 'https://ensa.uit.ac.ma/energy-efficiency-and-intelligent-buildings/',
                'description'  => 'Formation d\'ingénieurs spécialisés dans l\'efficacité énergétique, la gestion intelligente des bâtiments et les solutions durables. Elle couvre les systèmes de gestion de l\'énergie, les bâtiments connectés, les technologies de construction intelligente et les énergies renouvelables appliquées au bâtiment.',
                'objectifs'    => [
                    'Former des ingénieurs spécialisés dans les systèmes énergétiques du bâtiment',
                    'Maîtriser les techniques d\'optimisation de la consommation énergétique',
                    'Concevoir et gérer des bâtiments intelligents (domotique, IoT, BMS)',
                    'Intégrer les énergies renouvelables dans les solutions bâtiment',
                ],
                'competences'  => [
                    'Systèmes de gestion de l\'énergie dans le bâtiment',
                    'Technologies de bâtiments intelligents (BMS, KNX, SCADA)',
                    'Efficacité énergétique et audit énergétique',
                    'Énergies renouvelables appliquées au bâtiment',
                    'Climatisation, ventilation et chauffage',
                    'Réglementation thermique et certification HQE/LEED',
                ],
                'programme'    => [],
                'debouches'    => [
                    'Ingénieur en efficacité énergétique',
                    'Consultant en bâtiment intelligent',
                    'Chef de projet construction durable',
                    'Responsable HSE et transition énergétique',
                    'Auditeur énergétique',
                ],
                'acces'        => [
                    'Diplômes requis : 2 années préparatoires cycle ingénieur ou équivalent',
                    'Spécialités recommandées : Sciences de l\'ingénieur, Génie civil, Physique, Électrotechnique',
                ],
                'partenariats' => [],
            ],

            // ─── LICENCE UNIVERSITAIRE SPÉCIALISÉE ──────────────────────────────────
            [
                'slug'         => 'licence-universitaire-specialisee',
                'title'        => 'Licence Universitaire Spécialisée (LUS)',
                'category'     => 'formation_continue',
                'type'         => 'licence',
                'duree_annees' => 1,
                'source_url'   => 'https://ensa.uit.ac.ma/specialized-university-license/',
                'description'  => 'La Licence Universitaire Spécialisée est une formation continue de niveau Bac+3 proposée par l\'ENSA Kénitra pour permettre aux professionnels et aux titulaires d\'un DUT/BTS d\'acquérir une qualification supplémentaire dans un domaine spécialisé. Elle allie théorie et pratique pour répondre aux besoins concrets du marché du travail.',
                'objectifs'    => [
                    'Permettre aux professionnels de se spécialiser dans un domaine précis',
                    'Offrir une qualification de niveau licence à des titulaires de DUT/BTS',
                    'Répondre aux besoins des entreprises en compétences techniques spécialisées',
                ],
                'competences'  => [],
                'programme'    => [],
                'debouches'    => [
                    'Technicien supérieur spécialisé',
                    'Responsable technique en entreprise',
                    'Poursuite d\'études en Master',
                ],
                'acces'        => [
                    'Diplômes requis : DUT, BTS ou équivalent Bac+2 dans le domaine',
                    'Sélection sur dossier et/ou entretien',
                ],
                'partenariats' => [],
            ],

            // ─── MASTER UNIVERSITAIRE SPÉCIALISÉ ────────────────────────────────────
            [
                'slug'         => 'master-universitaire-specialise',
                'title'        => 'Master Universitaire Spécialisé (MUS)',
                'category'     => 'formation_continue',
                'type'         => 'master',
                'duree_annees' => 1,
                'source_url'   => 'https://ensa.uit.ac.ma/specialized-university-master/',
                'description'  => 'Le Master Universitaire Spécialisé est une formation continue de niveau Bac+5 proposée par l\'ENSA Kénitra. Elle s\'adresse aux ingénieurs et cadres souhaitant approfondir leur expertise dans un domaine technologique ou managérial, en combinant enseignements académiques et mise en pratique professionnelle.',
                'objectifs'    => [
                    'Permettre aux ingénieurs et cadres d\'approfondir leur expertise',
                    'Développer des compétences avancées en management et technologies',
                    'Favoriser la recherche appliquée et l\'innovation en entreprise',
                ],
                'competences'  => [],
                'programme'    => [],
                'debouches'    => [
                    'Expert technique ou managérial en entreprise',
                    'Consultant senior',
                    'Poursuite en Doctorat',
                    'Responsable R&D',
                ],
                'acces'        => [
                    'Diplômes requis : Diplôme d\'ingénieur, Master ou équivalent Bac+5',
                    'Expérience professionnelle souhaitée',
                    'Sélection sur dossier et entretien',
                ],
                'partenariats' => [],
            ],

        ];

        foreach ($formations as $data) {
            Formation::create($data);
        }
    }
}
