<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Major;

class MajorSeeder extends Seeder
{
    public function run()
    {
        $majors = [
            [
                'slug'        => 'genie-informatique',
                'title'       => 'Génie Informatique',
                'category'    => 'cycle_ingenieur',
                'type'        => 'ingenieur',
                'description' => 'Ingénieurs spécialisés en développement logiciel, algorithmes, bases de données, web et mobile.',
                'objectifs'   => [
                    'Concevoir et développer des logiciels complexes',
                    'Maîtriser les architectures systèmes et réseaux',
                    'Appliquer l\'IA et le Machine Learning aux problèmes réels',
                    'Gérer des projets informatiques de bout en bout',
                ],
                'competences' => [
                    'Programmation (Python, Java, C++)',
                    'Développement web full-stack',
                    'Bases de données et SQL',
                    'DevOps et CI/CD',
                    'Cybersécurité applicative',
                    'Intelligence artificielle',
                ],
                'debouches'   => [
                    'Développeur / Architecte logiciel',
                    'Ingénieur DevOps & Cloud',
                    'Data Scientist / ML Engineer',
                    'Chef de projet IT',
                    'Consultant en transformation digitale',
                ],
                'programme'   => [
                    'S1' => ['Algorithmique & Structures de données', 'Programmation C++', 'Mathématiques discrètes', 'Analyse & Algèbre'],
                    'S2' => ['Bases de données relationnelles', 'Développement web', 'Réseaux informatiques', 'Probabilités'],
                    'S3' => ['Génie logiciel', 'Systèmes d\'exploitation', 'IA & Machine Learning', 'Architecture logicielle'],
                    'S4' => ['Big Data & Cloud', 'Cybersécurité', 'DevOps', 'Projet intégré'],
                    'S5' => ['Stage industriel (6 mois)'],
                    'S6' => ['Projet de fin d\'études'],
                ],
                'acces'       => ['CNC après Classes Préparatoires (MPSI, MP, PSI)', 'Admission sur titre (Licence scientifique)'],
                'partenariats'=> ['Microsoft', 'Oracle', 'IBM', 'Capgemini', 'OCP Digital'],
                'duree_annees'=> 3,
                'source_url'  => 'https://ensa.uit.ac.ma',
            ],
            [
                'slug'        => 'reseaux-et-systemes-de-telecommunications',
                'title'       => 'Réseaux et Systèmes de Télécommunications',
                'category'    => 'cycle_ingenieur',
                'type'        => 'ingenieur',
                'description' => 'Ingénieurs en réseaux, télécommunications, cybersécurité et systèmes distribués.',
                'objectifs'   => [
                    'Concevoir des architectures réseaux sécurisées',
                    'Déployer des infrastructures télécom (4G/5G)',
                    'Maîtriser la cybersécurité et la cryptographie',
                    'Gérer des systèmes distribués et cloud',
                ],
                'competences' => [
                    'Protocoles TCP/IP & routage',
                    'Réseaux sans fil (Wi-Fi 6, 5G)',
                    'Cybersécurité & cryptographie',
                    'Administration systèmes Linux',
                    'Cloud & virtualisation',
                    'IoT & protocoles embarqués',
                ],
                'debouches'   => [
                    'Ingénieur réseau & télécom',
                    'Architecte infrastructure cloud',
                    'Consultant cybersécurité',
                    'Responsable SI',
                    'Ingénieur 5G / IoT',
                ],
                'programme'   => [
                    'S1' => ['Réseaux locaux & TCP/IP', 'Systèmes d\'exploitation', 'Electronique numérique', 'Mathématiques'],
                    'S2' => ['Réseaux sans fil', 'Cryptographie', 'Télécommunications', 'Signaux & systèmes'],
                    'S3' => ['Sécurité des réseaux', '5G & LTE', 'Cloud computing', 'VoIP & multimédia'],
                    'S4' => ['IoT & M2M', 'SDN & virtualisation', 'Big Data', 'Projet réseau'],
                    'S5' => ['Stage industriel (6 mois)'],
                    'S6' => ['Projet de fin d\'études'],
                ],
                'acces'       => ['CNC après Classes Préparatoires', 'Admission sur titre'],
                'partenariats'=> ['Maroc Telecom', 'Orange Maroc', 'Cisco', 'Huawei', 'AWS'],
                'duree_annees'=> 3,
                'source_url'  => 'https://ensa.uit.ac.ma',
            ],
            [
                'slug'        => 'genie-industriel',
                'title'       => 'Génie Industriel',
                'category'    => 'cycle_ingenieur',
                'type'        => 'ingenieur',
                'description' => 'Optimisation production, supply chain, qualité et automatisation industrielle.',
                'objectifs'   => [
                    'Optimiser les processus de production industrielle',
                    'Gérer la chaîne logistique de bout en bout',
                    'Mettre en oeuvre les démarches Lean et Six Sigma',
                    'Piloter des projets d\'automatisation',
                ],
                'competences' => [
                    'Lean Manufacturing & Kaizen',
                    'Supply Chain Management',
                    'Six Sigma & contrôle qualité',
                    'ERP (SAP, Odoo)',
                    'Simulation de production',
                    'Gestion de projet (PMP, Agile)',
                ],
                'debouches'   => [
                    'Ingénieur Lean / amélioration continue',
                    'Responsable supply chain',
                    'Chef de projet industriel',
                    'Consultant ERP',
                    'Ingénieur qualité & méthodes',
                ],
                'programme'   => [
                    'S1' => ['Gestion de production', 'Statistiques industrielles', 'Mécanique', 'Mathématiques'],
                    'S2' => ['Logistique & supply chain', 'Qualité & normes ISO', 'Recherche opérationnelle', 'Automatique'],
                    'S3' => ['Lean Manufacturing', 'ERP & systèmes d\'information', 'Simulation', 'Gestion de projet'],
                    'S4' => ['Six Sigma', 'Maintenance industrielle', 'Automatisation & robotique', 'Projet'],
                    'S5' => ['Stage industriel (6 mois)'],
                    'S6' => ['Projet de fin d\'études'],
                ],
                'acces'       => ['CNC après Classes Préparatoires', 'Admission sur titre'],
                'partenariats'=> ['OCP Group', 'Renault Maroc', 'Yazaki', 'Snecma', 'Delphi'],
                'duree_annees'=> 3,
                'source_url'  => 'https://ensa.uit.ac.ma',
            ],
            [
                'slug'        => 'genie-electrique',
                'title'       => 'Génie Électrique',
                'category'    => 'cycle_ingenieur',
                'type'        => 'ingenieur',
                'description' => 'Électrotechnique, électronique de puissance, machines électriques et automatique.',
                'objectifs'   => [
                    'Concevoir des systèmes électriques et d\'automatisation',
                    'Maîtriser l\'électronique de puissance',
                    'Développer des solutions d\'énergie renouvelable',
                    'Programmer des systèmes embarqués temps réel',
                ],
                'competences' => [
                    'Électrotechnique & machines électriques',
                    'Électronique de puissance',
                    'Automatique & régulation',
                    'Systèmes embarqués (STM32, Arduino)',
                    'Traitement du signal',
                    'Énergies renouvelables',
                ],
                'debouches'   => [
                    'Ingénieur électricien',
                    'Concepteur de systèmes embarqués',
                    'Ingénieur automaticien',
                    'Consultant en énergie durable',
                    'Ingénieur R&D électronique',
                ],
                'programme'   => [
                    'S1' => ['Circuits électriques', 'Électronique analogique', 'Mathématiques', 'Physique'],
                    'S2' => ['Machines électriques', 'Électronique de puissance', 'Automatique', 'Signaux'],
                    'S3' => ['Systèmes embarqués', 'Traitement du signal', 'Réseaux électriques', 'Énergie solaire'],
                    'S4' => ['Automates & SCADA', 'Éolien & hydraulique', 'IA appliquée', 'Projet'],
                    'S5' => ['Stage industriel (6 mois)'],
                    'S6' => ['Projet de fin d\'études'],
                ],
                'acces'       => ['CNC après Classes Préparatoires', 'Admission sur titre'],
                'partenariats'=> ['MASEN', 'ONEE', 'Schneider Electric', 'Siemens', 'ABB'],
                'duree_annees'=> 3,
                'source_url'  => 'https://ensa.uit.ac.ma',
            ],
            [
                'slug'        => 'genie-mecatronique',
                'title'       => 'Génie Mécatronique',
                'category'    => 'cycle_ingenieur',
                'type'        => 'ingenieur',
                'description' => 'Association de la mécanique, l\'électronique et l\'informatique pour des systèmes automatisés intelligents.',
                'objectifs'   => [
                    'Concevoir des systèmes mécatroniques complexes',
                    'Maîtriser la robotique et l\'automatisation',
                    'Programmer des systèmes temps réel embarqués',
                    'Intégrer l\'IA dans les systèmes physiques',
                ],
                'competences' => [
                    'Conception mécanique & CAO',
                    'Robotique & automatisation',
                    'Systèmes embarqués temps réel',
                    'Capteurs & actionneurs',
                    'Contrôle & commande',
                    'IoT industriel (IIoT)',
                ],
                'debouches'   => [
                    'Ingénieur robotique',
                    'Concepteur de systèmes automatisés',
                    'Ingénieur R&D mécatronique',
                    'Développeur IoT industriel',
                    'Chef de projet automatisation',
                ],
                'programme'   => [
                    'S1' => ['Mécanique des solides', 'Électronique', 'Algorithmique', 'Mathématiques'],
                    'S2' => ['Résistance des matériaux', 'Automatique', 'C embarqué', 'Capteurs & mesure'],
                    'S3' => ['Robotique', 'Systèmes temps réel', 'Fabrication assistée', 'Modélisation'],
                    'S4' => ['IIoT & industrie 4.0', 'IA embarquée', 'CAO & simulation', 'Projet'],
                    'S5' => ['Stage industriel (6 mois)'],
                    'S6' => ['Projet de fin d\'études'],
                ],
                'acces'       => ['CNC après Classes Préparatoires', 'Admission sur titre'],
                'partenariats'=> ['PSA Maroc', 'Safran', 'Valeo', 'Bosch', 'STMicroelectronics'],
                'duree_annees'=> 3,
                'source_url'  => 'https://ensa.uit.ac.ma',
            ],
            [
                'slug'        => 'genie-energetique-et-energies-renouvelables',
                'title'       => 'Génie Énergétique et Énergies Renouvelables',
                'category'    => 'cycle_ingenieur',
                'type'        => 'ingenieur',
                'description' => 'Conception de solutions énergétiques durables, efficacité énergétique et gestion des ressources renouvelables.',
                'objectifs'   => [
                    'Dimensionner des installations solaires et éoliennes',
                    'Optimiser l\'efficacité énergétique des bâtiments et industries',
                    'Concevoir des smart grids et réseaux intelligents',
                    'Conduire des audits énergétiques',
                ],
                'competences' => [
                    'Énergie solaire photovoltaïque & thermique',
                    'Énergie éolienne & hydraulique',
                    'Smart Grid & stockage d\'énergie',
                    'Thermodynamique appliquée',
                    'Audit & efficacité énergétique',
                    'Logiciels (PVsyst, MATLAB/Simulink)',
                ],
                'debouches'   => [
                    'Ingénieur en énergies renouvelables',
                    'Auditeur énergétique',
                    'Chef de projet solaire / éolien',
                    'Consultant efficacité énergétique',
                    'Responsable RSE & développement durable',
                ],
                'programme'   => [
                    'S1' => ['Thermodynamique', 'Mécanique des fluides', 'Électrotechnique', 'Mathématiques'],
                    'S2' => ['Énergie solaire', 'Énergie éolienne', 'Hydraulique', 'Transfert thermique'],
                    'S3' => ['Smart Grid', 'Stockage d\'énergie', 'Efficacité énergétique', 'Simulation énergétique'],
                    'S4' => ['Gestion de projets ENR', 'Audit énergétique', 'Finance de projets', 'Projet'],
                    'S5' => ['Stage industriel (6 mois)'],
                    'S6' => ['Projet de fin d\'études'],
                ],
                'acces'       => ['CNC après Classes Préparatoires', 'Admission sur titre'],
                'partenariats'=> ['MASEN', 'NAREVA', 'Enel Green Power', 'IRESEN', 'OCP'],
                'duree_annees'=> 3,
                'source_url'  => 'https://ensa.uit.ac.ma',
            ],
        ];

        foreach ($majors as $data) {
            Major::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
